#!/bin/bash
set -e
set -o pipefail

# Github Actions will mark a check as "neutral" (neither failed/succeeded) when you exit with code 78
# But this will terminate any other Actions running in parallel in the same workflow.
# Configuring this Environment Variable `END_IN_NEUTRAL=0` if no branch was deleted will let your workflow continue.
# Docs: https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#exit-codes-and-statuses
END_IN_NEUTRAL=${END_IN_NEUTRAL:-78}

ls
pwd
kubectl version

main(){
	action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
	merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
    ref=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
    owner=$(jq --raw-output .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH")
    repo=$(jq --raw-output .pull_request.head.repo.name "$GITHUB_EVENT_PATH")

    echo $GITHUB_EVENT_PATH
    echo "Action: $action"
    echo "Merged: $merged"
    echo "$Ref: ref"
    echo "$Owner: owner"
    echo "$Repo: repo"

    if [ "$action" = "open" ] || [ "$action" = "updated" ]; then
        echo "Running Tests"
        exit 0
    fi
    echo "A PR was not updated or opened, setting this build as Neutral!"
    exit $END_IN_NEUTRAL
}

main "$@"